[package]
name = "akv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infobip_sdk = "0.5.2"
tokio = "1.37.0"
reqwest = "0.12.2"
webbrowser = "0.5.2"
url = "2.2.2"
